import {StyleSheet} from 'react-native';

export const colors = {
  primary: '#2A1541',
  secondary: '#3A2151',
  accent: '#FF4081',
  highlight: '#9370DB',
  text: '#FFFFFF',
  textSecondary: '#AAAAAA',
  border: '#444444',
  borderCard: 'rgba(255, 255, 255, 0.12)',
  cardBackground: 'rgba(255, 255, 255, 0.05)',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 16,
    paddingTop: 60,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: colors.primary,
  },
  backHeader: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 16,
    paddingTop: 60,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: colors.primary,
    gap: 8,
  },
  screenTitle: {
    fontSize: 24,
    color: colors.text,
    fontFamily: 'PingFang-SC-Bold',
  },
  iconText: {
    fontSize: 24,
    color: colors.text,
  },
  scrollView: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  section: {
    marginBottom: 20,
  },
  recentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 27,
  },
  recentTitle: {
    fontSize: 16,
    color: colors.text,
    marginLeft: 8,
    fontFamily: 'PingFang-SC-Regular',
    textAlignVertical: 'center',
    opacity: 0.7,
  },
  subSection: {
    marginBottom: 27,
  },
  subSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  subSectionTitle: {
    fontSize: 16,
    color: colors.text,
    marginLeft: 8,
    fontFamily: 'PingFang-SC-Regular',
    textAlignVertical: 'center',
  },
  categoryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 8,
    marginHorizontal: 20,
    backgroundColor: colors.cardBackground,
    borderColor: colors.borderCard,
    borderWidth: 1,
    borderRadius: 16,
    gap: 14,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryDesc: {
    fontSize: 14,
    color: colors.text,
    fontFamily: 'PingFang-SC-Regular',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 20,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: 100,
  },
  footerButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButton: {
    width: 50,
    height: 50,
    backgroundColor: colors.accent,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  newNoteContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 26,
  },
  categorySelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderColor: colors.borderCard,
    backgroundColor: colors.cardBackground,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
  },
  categorySelectorText: {
    color: colors.text,
    fontSize: 14,
    fontFamily: 'PingFang-SC-Regular',
    opacity: 0.9,
  },
  dropdownOptions: {
    // position: 'absolute'
    // top: '100%',
    backgroundColor: colors.primary,
    // borderRadius: 8,
    // marginTop: 4,
    // elevation: 4,
    // shadowColor: '#000',
    // shadowOffset: {width: 0, height: 2},
    // shadowRadius: 4,
  },
  dropdownOption: {
    padding: 12,
  },
  dropdownOptionText: {
    color: colors.text,
    fontSize: 16,
  },
  noteInput: {
    maxHeight: 260,
    flex: 1,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderCard,
    backgroundColor: colors.cardBackground,
    color: colors.text,
    fontSize: 14,
    fontFamily: 'PingFang-SC-Regular',
    opacity: 0.9,
  },
  saveButtonContainer: {
    padding: 16,
  },
  saveButton: {
    backgroundColor: colors.accent,
    borderRadius: 25,
    paddingVertical: 8,
    alignItems: 'center',
  },
  saveButtonText: {
    textAlign: 'center',
    width: 168,
    color: colors.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  summaryHeader: {
    alignItems: 'center',
    marginVertical: 16,
  },
  robotPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  robotText: {
    fontSize: 50,
  },
  summaryItem: {
    backgroundColor: colors.secondary,
    borderRadius: 8,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  summaryItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  circleIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.highlight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  circleIconText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.text,
  },
  detailButton: {
    alignSelf: 'flex-end',
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    marginBottom: 8,
  },
  detailButtonText: {
    color: colors.text,
    fontSize: 14,
  },
  recordText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  settingItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  settingIconText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.highlight,
  },
  settingTitle: {
    fontSize: 16,
    color: colors.text,
  },
  deleteAccountContainer: {
    padding: 16,
  },
  deleteAccountButton: {
    backgroundColor: colors.accent,
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
  },
  deleteAccountText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
